### ISSUE TITLE
problem when compile the source code

### ISSUE THREAD

**Issue by Mia1349** [ChrisCreevey/clan_check#1]
Hello Chris!

Thank you for developing such a great tool! 

However, when I try to compile the file follow the manual, I ran into the following error message: 

clan_check.c: In function ‘main’:
clan_check.c:63:43: warning: comparison between pointer and zero character constant [-Wpointer-compare]
  if((treefile = fopen(treefilename, "r")) == '\0')   /* check to see if the file is there */
                                           ^~
clan_check.c:63:5: note: did you mean to dereference the pointer?
  if((treefile = fopen(treefilename, "r")) == '\0')   /* check to see if the file is there */
     ^
clan_check.c:68:45: warning: comparison between pointer and zero character constant [-Wpointer-compare]
  if((cladefile = fopen(cladefilename, "r")) == '\0')   /* check to see if the file is there */
                                             ^~
clan_check.c:68:5: note: did you mean to dereference the pointer?
  if((cladefile = fopen(cladefilename, "r")) == '\0')   /* check to see if the file is there */
     ^
clan_check.c:76:41: warning: comparison between pointer and zero character constant [-Wpointer-compare]
  if((outfile = fopen(outfilename, "w")) == '\0')   /* check to see if the file is there */
                                         ^~
clan_check.c:76:5: note: did you mean to dereference the pointer?
  if((outfile = fopen(outfilename, "w")) == '\0')   /* check to see if the file is there */
     ^
clan_check.c:360:41: warning: comparison between pointer and zero character constant [-Wpointer-compare]
            if(strstr(constraint,string) == '\0')

sorry that I do not know C very well and I have not been able to resolve this, could you help? 

Sincerely, 

Mia

**Comment by ChrisCreevey** [comment]
This issue was resolved by a pull request by @agalychnica
